name: spyre
dependencies:
- libgfortran=1.0=0
- openblas=0.2.14=1
- system=5.8=2
- freetype=2.5.2=2
- libpng=1.6.17=0
- matplotlib=1.4.3=np19py27_2
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.1=np19py27_0
- pip=7.0.3=py27_0
- pyparsing=2.0.3=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- readline=6.2=2
- setuptools=17.0=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- zlib=1.2.8=0
- pip:
  - cherrypy==3.7.0
  - dataspyre==0.1.9
  - jinja2==2.7.3
  - markupsafe==0.23
  - mock==1.0.1
  - nose==1.3.7
